name: Trigger GitLab CI

on:
  push:
    branches:
      - main

jobs:
  trigger-gitlab-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab CI Pipeline
        run: |
          echo "${{ secrets.TEST }}"
        env:
          GITLAB_PROJECT_ID: ${{ secrets.GITLAB_PROJECT_URL }}
          GITLAB_TRIGGER_TOKEN: ${{ secrets.GITLAB_TRIGGER_TOKEN }}
          TEST_TOKEN: ${{ secrets.TEST }}
