name: Trigger GitLab CI

on:
  push:
    branches:
      - main

jobs:
  trigger-gitlab-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab CI Pipeline
        run: |
          curl -X POST --fail -s -o /dev/null "${{ GITLAB_PROJECT_ID }}/trigger/pipeline" \
            --form "token=${{ GITLAB_TRIGGER_TOKEN }}" \
            --form "ref=main"
        env:
          GITLAB_PROJECT_ID: ${{ secrets.GITLAB_PROJECT_URL }}
          GITLAB_TRIGGER_TOKEN: ${{ secrets.GITLAB_TRIGGER_TOKEN }}
