main:
- {identifier: welcome, name: Start, weight: -99, url: /}
- {identifier: applications, name: Samples, weight: -97, url: /site/applications}
- {identifier: map, parent: applications, name: Map, weight: -98, url: /site/applications/map}
- {identifier: list, parent: applications, name: Applications A-Z, weight: -97,
  url: /site/applications/list}
- {identifier: support, name: Organisation, weight: -94, url: /site/support}
- {identifier: team, parent: support, name: Team, weight: -97, url: /site/support/team}
- {identifier: presentations, parent: support, name: Presentations, weight: -96, url: /site/presentations}
- {identifier: publications, parent: support, name: Publications, weight: -95,
  url: /site/publications}
- {identifier: bugs, parent: support, name: zu MyCoRe JIRA, weight: -94, url: 'http://mycore.atlassian.net'}
- {identifier: wiki, parent: support, name: zu MyCoRe Wiki, weight: -93, url: 'http://cmswiki.rrz.uni-hamburg.de/hummel#MyCoReWikiWiki'}
- {identifier: maven, parent: support, name: zu MyCoRe Maven, weight: -92, url: 'http://mvnrepository.com/artifact/org.mycore'}
