main:
- {identifier: welcome, name: Start, weight: -99, url: /}

- {identifier: features,                                        name: Funktionen,           weight: -98,      url: /site/features}
-   {identifier: features_datamodel,    parent: features,       name: Datenmodell,          weight: -98,      url: /site/features/datamodel}
-   {identifier: features_search,       parent: features,       name: Suche,                weight: -97,      url: /site/features/search}
-   {identifier: features_frontend,     parent: features,       name: Präsentation,         weight: -96,      url: /site/features/frontend}
-   {identifier: features_interfaces,   parent: features,       name: Schnittstellen,       weight: -95,      url: /site/features/interfaces}
-   {identifier: features_derivates,    parent: features,       name: Dateiverwaltung,      weight: -94,      url: /site/features/derivates}
-   {identifier: features_acl,          parent: features,       name: Rechteverwaltung,     weight: -93,      url: /site/features/acl}

- {identifier: applications,                                    name: Anwendungen,          weight: -97,      url: /site/applications}
-   {identifier: map,                   parent: applications,   name: Karte,                weight: -98,      url: /site/applications/map}
-   {identifier: list,                  parent: applications,   name: von A bis Z,          weight: -97,      url: /site/applications/list}
-   {identifier: mirdemo,               parent: applications,   name: MIR Demo,             weight: -96,      url: /site/applications/mirdemo}

- {identifier: download,                                        name: Download,             weight: -96,      url: /site/download}
-   {identifier: dl_mycore,               parent: download,       name: MyCoRe,               weight: -98,      url: /site/download/dl_mycore}
-     {identifier: release,                 parent: dl_mycore,      name: aktuelles LTS-Release,  weight: -98,      url: /site/download/dl_mycore/release}
-     {identifier: changelog,               parent: dl_mycore,      name: Changelog,            weight: -97,      url: /site/download/dl_mycore/changelog}
-     {identifier: archive,                 parent: dl_mycore,      name: Archiv,               weight: -96,      url: /site/download/dl_mycore/archive}
-   {identifier: dl_mir,                  parent: download,       name: MIR,                  weight: -97,      url: /site/download/dl_mir}
-     {identifier: mir_release,        parent: dl_mir,         name: aktuelles LTS-Release,      weight: -99,      url: /site/download/dl_mir/mir_release}
-     {identifier: mir_changelog,           parent: dl_mir,         name: Changelog,            weight: -97,      url: /site/download/dl_mir/mir_changelog}
-   {identifier: license,                 parent: download,       name: Lizenzbedingungen,    weight: -95,      url: /site/download/license}
-   {identifier: logos,                   parent: download,       name: Material,             weight: -94,      url: /site/download/logos}

- {identifier: documentation,                                         name: Dokumentation,               weight: -95,      url: /documentation}
- {identifier: blog,                                               name: Blog,                         weight: -94,      url: /blog}

- {identifier: community,                                            name: Organisation,                 weight: -93,     url: /site/community}
-   {identifier: contact,               parent: community,             name: Kontaktaufnahme,              weight: -98,     url: /site/community/contact}
-   {identifier: team,                  parent: community,             name: Team,                         weight: -97,     url: /site/community/team}
-   {identifier: workshops,             parent: community,             name: Workshops,                    weight: -96,     url: /site/community/workshops}
-   {identifier: bugs,                  parent: community,             name: zum JIRA,               weight: -94,     url: 'https://mycore.atlassian.net'}
-   {identifier: wiki,                  parent: community,             name: zum Wiki,               weight: -93,     url: 'https://cmswiki.rrz.uni-hamburg.de/hummel#MyCoReWikiWiki'}
-   {identifier: maven,                 parent: community,             name: zu Maven,               weight: -92,     url: 'https://mvnrepository.com/artifact/org.mycore'}
-   {identifier: github,                parent: community,             name: zu Github,              weight: -91,     url: 'https://github.com/MyCoRe-Org'}
